export const adminAgentLogsStyles = {
  wrap: { maxWidth: 980, mx: "auto", display: "grid", gridTemplateColumns: { xs: "1fr", lg: "1.3fr .9fr" }, gap: 2 },
  card: { p: "20px 22px", borderRadius: "16px" },
  title: { fontFamily: '"Source Serif 4", serif', fontSize: 17, fontWeight: 600 },
  row: { display: "flex", alignItems: "center", gap: "12px", py: "12px", borderTop: "1px solid", borderTopColor: "divider" },
  statusBadge: {
    fontSize: 11,
    fontWeight: 700,
    px: "9px",
    py: "3px",
    borderRadius: "6px",
    fontFamily: '"Space Mono", monospace',
    textTransform: "uppercase",
    letterSpacing: ".04em",
    whiteSpace: "nowrap",
  },
  promptCard: { p: "20px 22px", borderRadius: "16px", display: "grid", alignContent: "start", gap: "12px" },
  promptLabel: {
    fontSize: 11,
    color: "text.disabled",
    fontFamily: '"Space Mono", monospace',
    textTransform: "uppercase",
    letterSpacing: ".08em",
  },
  promptTextarea: {
    width: "100%",
    minHeight: "190px",
    border: "1px solid",
    borderColor: "divider",
    borderRadius: "12px",
    p: "12px",
    fontFamily: '"Space Mono", monospace',
    fontSize: "12.5px",
    lineHeight: "1.6",
    backgroundColor: "background.default",
    color: "text.primary",
    resize: "vertical",
    outline: "none",
  },
};
