export const dailyChallengeStyles = {
  root: {
    minHeight: "100vh",
    backgroundColor: "background.default",
    display: "flex",
  },
  shell: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    overflow: "hidden",
  },
  scrollBody: {
    flex: 1,
    overflow: "auto",
    px: { xs: 2, md: 3.75 },
    pt: { xs: 2.5, md: 3.75 },
    pb: { xs: 5, md: 7.5 },
  },
  contentWrap: { maxWidth: 920, mx: "auto", display: "grid", gap: 1.4 },
  heroCard: {
    p: "28px 30px",
    borderRadius: "22px",
    color: "primary.contrastText",
    backgroundColor: "primary.main",
    position: "relative",
    overflow: "hidden",
  },
  heroOrb: {
    position: "absolute",
    right: -30,
    top: -30,
    width: 150,
    height: 150,
    borderRadius: "50%",
    backgroundColor: "rgba(255,255,255,.06)",
  },
  heroTopRow: {
    display: "flex",
    alignItems: "center",
    gap: 1.2,
    position: "relative",
  },
  heroDate: {
    fontSize: 12,
    letterSpacing: ".14em",
    textTransform: "uppercase",
    opacity: 0.8,
    fontFamily: '"Space Mono", monospace',
  },
  doneTodayBadge: {
    fontSize: 11,
    fontWeight: 700,
    px: 1.2,
    py: 0.4,
    borderRadius: "20px",
    background: "rgba(255,255,255,.18)",
    fontFamily: '"Space Mono", monospace',
    letterSpacing: ".04em",
  },
  heroTitle: {
    fontSize: 30,
    mt: 1,
    position: "relative",
    letterSpacing: "-.02em",
  },
  heroSubtitle: {
    mt: 0.75,
    opacity: 0.88,
    lineHeight: 1.5,
    maxWidth: 440,
    position: "relative",
    fontSize: 14.5,
  },
  heroButton: {
    mt: 2.5,
    bgcolor: "background.paper",
    color: "primary.main",
    fontWeight: 700,
    px: 3.25,
    py: 1.6,
    borderRadius: "13px",
    position: "relative",
    "&:hover": { transform: "translateY(-1px)" },
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 1,
  },
  statCard: {
    p: 2,
    borderRadius: "14px",
    borderColor: "divider",
    textAlign: "center",
  },
  statLabel: { fontSize: 12, color: "text.secondary" },
  weekCard: { p: "20px 22px", borderRadius: "16px", borderColor: "divider" },
  weekTitle: {
    fontFamily: '"Source Serif 4", serif',
    fontSize: 16,
    fontWeight: 600,
    mb: 2,
  },
  weekRow: { display: "flex", gap: 0.75 },
  weekDayCol: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 0.75,
  },
  levelCard: { p: "20px 22px", borderRadius: "16px", borderColor: "divider" },
  levelHead: { display: "flex", alignItems: "center", gap: 2, mb: 2 },
  levelBadge: {
    width: 52,
    height: 52,
    flexShrink: 0,
    borderRadius: "14px",
    bgcolor: "primary.main",
    color: "primary.contrastText",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    lineHeight: 1,
  },
  levelKicker: {
    fontSize: 9,
    letterSpacing: ".08em",
    opacity: 0.8,
    fontFamily: '"Space Mono", monospace',
  },
  levelNumber: {
    fontFamily: '"Source Serif 4", serif',
    fontSize: 20,
    fontWeight: 700,
  },
  grow: { flex: 1, minWidth: 0 },
  levelMetaRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    mb: 0.75,
  },
  levelMetaTitle: {
    fontFamily: '"Source Serif 4", serif',
    fontSize: 16,
    fontWeight: 600,
  },
  levelMetaSub: {
    fontSize: 12,
    color: "text.disabled",
    fontFamily: '"Space Mono", monospace',
  },
  levelTrack: {
    height: 8,
    borderRadius: 99,
    bgcolor: "background.default",
    overflow: "hidden",
  },
  levelTrackFill: { height: "100%", bgcolor: "primary.main" },
  levelFoot: { fontSize: 11.5, color: "text.disabled", mt: 0.6 },
  nextButton: { px: 3, py: 1.2, borderRadius: "12px" },
} as const;

