export const dashboardStyles = {
  root: {
    minHeight: "100vh",
    backgroundColor: "background.default",
    display: "flex",
  },
  shell: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    overflow: "hidden",
  },
  scrollBody: {
    flex: 1,
    overflow: "auto",
    px: { xs: 2, md: 3.75 },
    pt: { xs: 2.5, md: 3.75 },
    pb: { xs: 5, md: 7.5 },
  },
  wrap: { maxWidth: 1160, mx: "auto" },
  heroRow: { display: "flex", gap: 2, flexWrap: "wrap", mb: 2.75 },
  heroCopy: { flex: 1, minWidth: 300 },
  heroCard: {
    flex: 1,
    minWidth: 300,
    borderRadius: "18px",
    p: 2.5,
    display: "flex",
    alignItems: "center",
    gap: 2.25,
    color: "primary.contrastText",
    backgroundColor: "primary.main",
  },
  heroGreeting: { fontSize: 29 },
  heroMessage: { color: "text.secondary", fontSize: 15, mt: 0.5 },
  heroCardContent: { flex: 1 },
  continueLabel: {
    fontFamily: '"Space Mono", monospace',
    fontSize: 11,
    letterSpacing: ".12em",
    textTransform: "uppercase",
    opacity: 0.86,
  },
  continueTopic: {
    fontFamily: '"Source Serif 4", serif',
    fontSize: 19,
    fontWeight: 600,
    lineHeight: 1.25,
    mt: 0.4,
  },
  continueProgressTrack: {
    mt: 1.4,
    height: 6,
    borderRadius: 99,
    backgroundColor: "rgba(255,255,255,.22)",
    overflow: "hidden",
  },
  continueProgressFill: {
    height: "100%",
    borderRadius: 99,
    backgroundColor: "background.paper",
  },
  continueProgressText: { mt: 0.75, fontSize: 12, opacity: 0.9 },
  continueBadge: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    backgroundColor: "background.paper",
    color: "primary.main",
    display: "grid",
    placeItems: "center",
    fontSize: 20,
    cursor: "pointer",
    userSelect: "none",
    "&:hover": {
      transform: "scale(1.04)",
    },
  },
  statsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 2, mb: 2.75 },
  statCard: { p: 2.25, borderRadius: "16px" },
  statCardLabel: { fontSize: 12.5, color: "text.secondary" },
  statCardValue: { fontSize: 31, mt: 0.6 },
  panelsGrid: { display: "grid", gridTemplateColumns: { xs: "1fr", lg: "1.15fr .85fr" }, gap: 2, mb: 2.75 },
  panel: { borderRadius: "16px", p: "20px 22px", boxShadow: "0 1px 2px rgba(24,24,32,.05)" },
  panelHeaderRow: { display: "flex", alignItems: "baseline", justifyContent: "space-between", mb: 2.25 },
  panelTitle: { fontFamily: '"Source Serif 4", serif', fontSize: 17, fontWeight: 600 },
  panelMeta: { fontFamily: '"Space Mono", monospace', color: "text.disabled", fontSize: 12 },
  barsRow: { display: "flex", alignItems: "flex-end", gap: 1.5, height: 150 },
  barColumn: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 1, justifyContent: "flex-end", height: "100%" },
  barFill: { width: "100%", borderRadius: "7px 7px 3px 3px", minHeight: 6 },
  barDayLabel: { fontSize: 11, color: "text.disabled", fontWeight: 600 },
  subjectTitle: { fontFamily: '"Source Serif 4", serif', fontSize: 17, fontWeight: 600, mb: 2 },
  subjectList: { display: "grid", gap: "13px" },
  subjectRowHead: { display: "flex", justifyContent: "space-between", mb: "5px" },
  subjectName: { fontSize: 12.5, fontWeight: 500 },
  subjectAccuracy: { fontFamily: '"Space Mono", monospace', fontSize: 12, color: "text.secondary" },
  subjectTrack: { height: 7, borderRadius: 99, backgroundColor: "background.default", overflow: "hidden" },
  recommendationsHead: { display: "flex", justifyContent: "space-between", alignItems: "baseline", mb: 1.5 },
  recommendationsTitle: { fontFamily: '"Source Serif 4", serif', fontSize: 18, fontWeight: 600 },
  recommendationsSubtitle: { fontSize: 12.5, color: "text.secondary" },
  recommendationsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 2 },
  recommendationCard: {
    p: 2.25,
    borderRadius: "16px",
    cursor: "pointer",
    transition: "transform .18s ease, border-color .18s ease",
    "&:hover": {
      borderColor: "primary.main",
      transform: "translateY(-2px)",
    },
  },
  recommendationTag: {
    display: "inline-flex",
    px: 1,
    py: 0.4,
    borderRadius: "8px",
    fontFamily: '"Space Mono", monospace',
    fontSize: 10,
    letterSpacing: ".08em",
    textTransform: "uppercase",
    color: "primary.main",
    backgroundColor: "primary.light",
  },
  recommendationTopic: {
    fontFamily: '"Source Serif 4", serif',
    fontSize: 16,
    fontWeight: 600,
    lineHeight: 1.34,
    mt: 1.2,
  },
  recommendationReason: { mt: 0.75, fontSize: 12.5, color: "text.secondary" },
  recommendationAction: { mt: 1.5, fontSize: 13, fontWeight: 600, color: "primary.main" },
};

export const statDeltaSx = (tone: "good" | "muted") => ({
  mt: 0.4,
  fontSize: 12.5,
  fontWeight: 600,
  color: tone === "good" ? "success.main" : "text.disabled",
});

export const weeklyBarFillSx = (heightPercent: number, color: string) => ({
  ...dashboardStyles.barFill,
  height: `${heightPercent}%`,
  backgroundColor: color,
});

export const subjectFillSx = (widthPercent: number, color: string) => ({
  width: `${widthPercent}%`,
  height: "100%",
  borderRadius: 99,
  backgroundColor: color,
});

export const continueProgressFillSx = (width: string) => ({
  ...dashboardStyles.continueProgressFill,
  width,
});
