import { Box, Button, Chip, Paper, Typography } from "@mui/material";
import type { AppScreen } from "../../../../app/screens";
import type { AdminDraft, AdminDraftStatus } from "../../admin.types";
import {
  adminReviewQueueStyles,
  difficultyToneSx,
  optionLetterToneSx,
  optionToneSx,
} from "./admin-review-queue.styles";
import { adminSharedStyles } from "../../admin-shared.styles";
import { PracticeTopbar } from "../../../practice";

type AdminReviewQueuePageProps = {
  drafts: AdminDraft[];
  onResolveDraft: (draftId: string, status: AdminDraftStatus) => void;
  onNavigateScreen?: (screen: AppScreen) => void;
};

export function AdminReviewQueuePage(props: AdminReviewQueuePageProps) {
  const { drafts, onResolveDraft, onNavigateScreen } = props;

  const pendingDrafts = drafts.filter((draft) => draft.status === "pending");

  return (
    <Box sx={adminSharedStyles.shell}>
        <PracticeTopbar
          currentScreen="adminReviewQueue"
          title="Review Queue"
          subtitle="Approve, edit, or reject generated draft MCQs"
          searchPlaceholder="Search Drafts"
          onOpenGlobalSearch={() => onNavigateScreen?.("globalSearch")}
          onOpenSettings={() => onNavigateScreen?.("settingsProfile")}
          onNavigateScreen={onNavigateScreen}
        />

        <Box sx={adminSharedStyles.scrollBody}>
          <Box sx={adminReviewQueueStyles.wrap}>
            <Typography sx={adminReviewQueueStyles.intro}>
              {pendingDrafts.length} MCQs awaiting review · generated by the MCQ + Validation + Duplicate-Detection agents
            </Typography>

            <Box sx={adminReviewQueueStyles.list}>
              {drafts.map((draft) => {
                const resolved = draft.status !== "pending";

                return (
                  <Paper
                    key={draft.id}
                    variant="outlined"
                    sx={{ ...adminReviewQueueStyles.draftCard, opacity: resolved ? 0.65 : 1 }}
                  >
                      <Box sx={adminReviewQueueStyles.topRow}>
                        <Box sx={{ ...adminReviewQueueStyles.chip, bgcolor: "primary.light", color: "primary.main" }}>
                          {draft.subject}
                        </Box>
                        <Typography sx={adminReviewQueueStyles.bodyLabel}>
                          {draft.body}
                        </Typography>
                        <Typography sx={{ ...adminReviewQueueStyles.bodyLabel, ...difficultyToneSx(draft.difficulty) }}>
                          {draft.difficulty}
                        </Typography>
                        <Box sx={{ flex: 1 }} />
                      <Chip
                        size="small"
                        label={draft.validation}
                        sx={{
                          bgcolor: draft.validation === "Validated" ? "success.light" : "warning.light",
                        }}
                      />
                      <Chip
                        size="small"
                        label={draft.duplicate}
                        sx={{
                          bgcolor: draft.duplicate === "No duplicate" ? "background.default" : "error.light",
                        }}
                      />
                      {resolved && <Chip size="small" label={draft.status} color={draft.status === "approved" ? "success" : "error"} />}
                    </Box>

                    <Typography sx={adminReviewQueueStyles.question}>{draft.question}</Typography>

                    <Box sx={adminReviewQueueStyles.optionsCol}>
                      {draft.options.map((option, optionIndex) => (
                        <Box
                          key={`${draft.id}-${optionIndex}`}
                          sx={{ ...adminReviewQueueStyles.optionRow, ...optionToneSx(optionIndex === draft.correctIndex) }}
                        >
                          <Box sx={{ ...adminReviewQueueStyles.optionLetter, ...optionLetterToneSx(optionIndex === draft.correctIndex) }}>
                            {String.fromCharCode(65 + optionIndex)}
                          </Box>
                          <Typography sx={{ flex: 1 }}>{option}</Typography>
                        </Box>
                      ))}
                    </Box>

                    <Typography sx={adminReviewQueueStyles.explanation}>
                      {draft.explanation}
                    </Typography>

                    <Box sx={adminReviewQueueStyles.actions}>
                      <Button
                        variant="contained"
                        color="success"
                        disabled={resolved}
                        sx={{ px: "18px", py: "9px", borderRadius: "10px", fontSize: 13, fontWeight: 600 }}
                        onClick={() => onResolveDraft(draft.id, "approved")}
                      >
                        Approve & publish
                      </Button>
                      <Button variant="outlined" disabled={resolved} sx={{ px: "18px", py: "9px", borderRadius: "10px", fontSize: 13, fontWeight: 600 }}>Edit</Button>
                      <Button
                        variant="outlined"
                        color="error"
                        disabled={resolved}
                        sx={{ px: "18px", py: "9px", borderRadius: "10px", fontSize: 13, fontWeight: 600 }}
                        onClick={() => onResolveDraft(draft.id, "rejected")}
                      >
                        Reject
                      </Button>
                    </Box>
                  </Paper>
                );
              })}
            </Box>
          </Box>
        </Box>
      </Box>
  );
}
