import { useState } from "react";
import {
  Alert,
  Box,
  Button,
  Chip,
  CircularProgress,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  MenuItem,
  Select,
  TextField,
  Typography,
  Paper,
} from "@mui/material";
import type { AppScreen } from "../../../../app/screens";
import { toApiErrorMessage } from "../../../../api/error";
import {
  useApproveAdminQuestionMutation,
  useEditAdminQuestionMutation,
  useGetAdminReviewQueueQuery,
  useRejectAdminQuestionMutation,
} from "../../../../api/admin/admin-review-queue.endpoints";
import type { AdminReviewItem } from "../../../../api/admin/admin.types";
import {
  adminReviewQueueStyles,
  difficultyToneSx,
  optionLetterToneSx,
  optionToneSx,
} from "./admin-review-queue.styles";
import { adminSharedStyles } from "../../admin-shared.styles";
import { PracticeTopbar } from "../../../practice";

type AdminReviewQueuePageProps = {
  onNavigateScreen?: (screen: AppScreen) => void;
};

const REJECT_REASON = "Rejected by reviewer";

export function AdminReviewQueuePage(props: AdminReviewQueuePageProps) {
  const { onNavigateScreen } = props;

  const queueQuery = useGetAdminReviewQueueQuery();
  const [approve] = useApproveAdminQuestionMutation();
  const [reject] = useRejectAdminQuestionMutation();
  const [editQuestion, editState] = useEditAdminQuestionMutation();
  const [actingId, setActingId] = useState<string | null>(null);
  const [editingDraft, setEditingDraft] = useState<AdminReviewItem | null>(null);
  const [editForm, setEditForm] = useState<EditForm | null>(null);

  const drafts = queueQuery.data?.items ?? [];

  async function handleApprove(draft: AdminReviewItem): Promise<void> {
    setActingId(draft.id);
    try {
      await approve(draft.id).unwrap();
    } finally {
      setActingId(null);
    }
  }

  async function handleReject(draft: AdminReviewItem): Promise<void> {
    setActingId(draft.id);
    try {
      await reject({ id: draft.id, reason: REJECT_REASON }).unwrap();
    } finally {
      setActingId(null);
    }
  }

  function handleOpenEdit(draft: AdminReviewItem): void {
    setEditingDraft(draft);
    setEditForm({
      questionText: draft.questionText,
      options: [...draft.options],
      correctIndex: draft.correctIndex,
      explanation: draft.explanation ?? "",
    });
  }

  function handleCloseEdit(): void {
    setEditingDraft(null);
    setEditForm(null);
  }

  async function handleSaveEdit(): Promise<void> {
    if (!editingDraft || !editForm) {
      return;
    }
    await editQuestion({
      id: editingDraft.id,
      questionText: editForm.questionText,
      options: editForm.options,
      correctIndex: editForm.correctIndex,
      explanation: editForm.explanation,
    }).unwrap();
    handleCloseEdit();
  }

  return (
    <Box sx={adminSharedStyles.shell}>
        <PracticeTopbar
          currentScreen="adminReviewQueue"
          title="Review Queue"
          subtitle="Approve, edit, or reject generated draft MCQs"
          searchPlaceholder="Search Drafts"
          onOpenGlobalSearch={() => onNavigateScreen?.("globalSearch")}
          onOpenSettings={() => onNavigateScreen?.("settingsProfile")}
          onNavigateScreen={onNavigateScreen}
        />

        <Box sx={adminSharedStyles.scrollBody}>
          <Box sx={adminReviewQueueStyles.wrap}>
            <Typography sx={adminReviewQueueStyles.intro}>
              {queueQuery.data?.total ?? 0} MCQs awaiting review · generated by the MCQ + Validation + Duplicate-Detection agents
            </Typography>

            {queueQuery.isError && (
              <Alert severity="error" sx={{ borderRadius: 2, mb: 1.5 }}>
                Could not load the review queue. {toApiErrorMessage(queueQuery.error, "Please try again.")}
              </Alert>
            )}

            {queueQuery.isLoading && (
              <Box sx={{ display: "flex", justifyContent: "center", py: 6 }}>
                <CircularProgress size={26} />
              </Box>
            )}

            {!queueQuery.isLoading && drafts.length === 0 && !queueQuery.isError && (
              <Typography sx={{ fontSize: 13.5, color: "text.secondary" }}>
                Nothing pending review right now.
              </Typography>
            )}

            <Box sx={adminReviewQueueStyles.list}>
              {drafts.map((draft) => {
                const busy = actingId === draft.id;

                return (
                  <Paper key={draft.id} variant="outlined" sx={{ ...adminReviewQueueStyles.draftCard, opacity: busy ? 0.65 : 1 }}>
                      <Box sx={adminReviewQueueStyles.topRow}>
                        <Box sx={{ ...adminReviewQueueStyles.chip, bgcolor: "primary.light", color: "primary.main" }}>
                          {draft.subject.name}
                        </Box>
                        {draft.exam && (
                          <Typography sx={adminReviewQueueStyles.bodyLabel}>
                            {draft.exam.body}
                          </Typography>
                        )}
                        <Typography sx={{ ...adminReviewQueueStyles.bodyLabel, ...difficultyToneSx(capitalize(draft.difficulty)) }}>
                          {capitalize(draft.difficulty)}
                        </Typography>
                        <Box sx={{ flex: 1 }} />
                      <Chip
                        size="small"
                        label={draft.flags.validationText}
                        sx={{
                          bgcolor: draft.flags.validation === "VALIDATED" ? "success.light" : "warning.light",
                        }}
                      />
                      <Chip
                        size="small"
                        label={draft.flags.duplicateText}
                        sx={{
                          bgcolor: draft.flags.duplicate === "NO_DUPLICATE" ? "background.default" : "error.light",
                        }}
                      />
                    </Box>

                    <Typography sx={adminReviewQueueStyles.question}>{draft.questionText}</Typography>

                    <Box sx={adminReviewQueueStyles.optionsCol}>
                      {draft.options.map((option, optionIndex) => (
                        <Box
                          key={`${draft.id}-${optionIndex}`}
                          sx={{ ...adminReviewQueueStyles.optionRow, ...optionToneSx(optionIndex === draft.correctIndex) }}
                        >
                          <Box sx={{ ...adminReviewQueueStyles.optionLetter, ...optionLetterToneSx(optionIndex === draft.correctIndex) }}>
                            {String.fromCharCode(65 + optionIndex)}
                          </Box>
                          <Typography sx={{ flex: 1 }}>{option}</Typography>
                        </Box>
                      ))}
                    </Box>

                    {draft.explanation && (
                      <Typography sx={adminReviewQueueStyles.explanation}>
                        {draft.explanation}
                      </Typography>
                    )}

                    <Box sx={adminReviewQueueStyles.actions}>
                      <Button
                        variant="contained"
                        color="success"
                        disabled={busy}
                        sx={{ px: "18px", py: "9px", borderRadius: "10px", fontSize: 13, fontWeight: 600 }}
                        onClick={() => void handleApprove(draft)}
                      >
                        Approve & publish
                      </Button>
                      <Button
                        variant="outlined"
                        disabled={busy}
                        sx={{ px: "18px", py: "9px", borderRadius: "10px", fontSize: 13, fontWeight: 600 }}
                        onClick={() => handleOpenEdit(draft)}
                      >
                        Edit
                      </Button>
                      <Button
                        variant="outlined"
                        color="error"
                        disabled={busy}
                        sx={{ px: "18px", py: "9px", borderRadius: "10px", fontSize: 13, fontWeight: 600 }}
                        onClick={() => void handleReject(draft)}
                      >
                        Reject
                      </Button>
                    </Box>
                  </Paper>
                );
              })}
            </Box>
          </Box>
        </Box>

        <Dialog open={editingDraft !== null} onClose={handleCloseEdit} maxWidth="sm" fullWidth>
          <DialogTitle>Edit draft MCQ</DialogTitle>
          <DialogContent sx={{ display: "grid", gap: 2, pt: "8px !important" }}>
            {editState.isError && (
              <Alert severity="error" sx={{ borderRadius: 2 }}>
                {toApiErrorMessage(editState.error, "Could not save this edit.")}
              </Alert>
            )}

            <TextField
              label="Question"
              multiline
              minRows={2}
              fullWidth
              value={editForm?.questionText ?? ""}
              onChange={(e) => setEditForm((f) => (f ? { ...f, questionText: e.target.value } : f))}
            />

            {editForm?.options.map((option, index) => (
              <TextField
                key={index}
                label={`Option ${String.fromCharCode(65 + index)}`}
                fullWidth
                value={option}
                onChange={(e) =>
                  setEditForm((f) => {
                    if (!f) return f;
                    const options = [...f.options];
                    options[index] = e.target.value;
                    return { ...f, options };
                  })
                }
              />
            ))}

            <Select
              value={editForm?.correctIndex ?? 0}
              onChange={(e) => setEditForm((f) => (f ? { ...f, correctIndex: Number(e.target.value) } : f))}
            >
              {editForm?.options.map((_, index) => (
                <MenuItem key={index} value={index}>
                  Correct answer: {String.fromCharCode(65 + index)}
                </MenuItem>
              ))}
            </Select>

            <TextField
              label="Explanation"
              multiline
              minRows={2}
              fullWidth
              value={editForm?.explanation ?? ""}
              onChange={(e) => setEditForm((f) => (f ? { ...f, explanation: e.target.value } : f))}
            />
          </DialogContent>
          <DialogActions sx={{ px: 3, pb: 2 }}>
            <Button onClick={handleCloseEdit} disabled={editState.isLoading}>
              Cancel
            </Button>
            <Button variant="contained" onClick={() => void handleSaveEdit()} disabled={editState.isLoading}>
              Save changes
            </Button>
          </DialogActions>
        </Dialog>
      </Box>
  );
}

type EditForm = {
  questionText: string;
  options: string[];
  correctIndex: number;
  explanation: string;
};

function capitalize(value: string): string {
  return value.charAt(0) + value.slice(1).toLowerCase();
}
