export const notificationSettingsStyles = {
  root: {
    minHeight: "100vh",
    backgroundColor: "background.default",
    display: "flex",
  },
  appShell: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    overflow: "hidden",
  },
  scrollBody: {
    flex: 1,
    overflow: "auto",
    px: { xs: 2, md: 3.75 },
    pt: { xs: 2.5, md: 3.75 },
    pb: { xs: 5, md: 7.5 },
  },
  contentWrap: {
    maxWidth: 680,
    mx: "auto",
    animation: "fadeUp .4s ease both",
  },
  sectionCard: {
    p: "22px 24px",
    borderRadius: "16px",
    boxShadow: "0 1px 2px rgba(24,24,32,.05)",
  },
  sectionCardSpaced: {
    p: "22px 24px",
    borderRadius: "16px",
    boxShadow: "0 1px 2px rgba(24,24,32,.05)",
    mb: 2,
  },
  sectionTitle: {
    fontFamily: '"Source Serif 4", serif',
    fontSize: 17,
    fontWeight: 600,
  },
  sectionTitleTight: {
    fontFamily: '"Source Serif 4", serif',
    fontSize: 17,
    fontWeight: 600,
    mb: 0.5,
  },
  sectionTitleWithGap: {
    fontFamily: '"Source Serif 4", serif',
    fontSize: 17,
    fontWeight: 600,
    mb: "18px",
  },
  sectionTitleSoftGap: {
    fontFamily: '"Source Serif 4", serif',
    fontSize: 17,
    fontWeight: 600,
    mb: "8px",
  },
  sectionSub: {
    fontSize: 13,
    color: "text.secondary",
  },
  row: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    py: "14px",
    borderTop: "1px solid",
    borderColor: "divider",
  },
  channelRow: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    py: "15px",
    mt: "14px",
    borderTop: "1px solid",
    borderColor: "divider",
  },
  iconBadge: {
    width: 38,
    height: 38,
    flex: "none",
    borderRadius: "10px",
    bgcolor: "background.default",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 17,
  },
  rowTitle: {
    fontWeight: 600,
    fontSize: 14.5,
  },
  rowDesc: {
    fontSize: 13,
    color: "text.secondary",
    mt: "1px",
  },
  timingHeaderRow: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    pb: "16px",
    borderBottom: "1px solid",
    borderColor: "divider",
  },
  quietRow: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    pt: "16px",
  },
  quietPanel: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    mt: "14px",
    p: "14px 16px",
    borderRadius: "12px",
    bgcolor: "background.default",
    flexWrap: "wrap",
  },
  digestWrap: {
    pt: "16px",
    mt: "6px",
    borderTop: "1px solid",
    borderColor: "divider",
  },
  digestRow: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
  },
  grow: { flex: 1 },
  quietLabel: { fontSize: 13, color: "text.secondary" },
  categoryTitle: { fontWeight: 600, fontSize: 14.5, flex: 1 },
  digestTitle: {
    fontWeight: 600,
    fontSize: 14.5,
    mb: "12px",
  },
};

export const toggleSx = (on: boolean) => ({
  width: 46,
  height: 26,
  borderRadius: "20px",
  flex: "none",
  cursor: "pointer",
  position: "relative",
  transition: "background .2s",
  bgcolor: on ? "primary.main" : "divider",
});

export const knobSx = (on: boolean) => ({
  position: "absolute",
  top: 3,
  left: on ? 23 : 3,
  width: 20,
  height: 20,
  borderRadius: "50%",
  bgcolor: "#fff",
  transition: "left .2s",
  boxShadow: "0 1px 3px rgba(0,0,0,.3)",
});

export const digestChipSx = (active: boolean) => ({
  px: "15px",
  py: "8px",
  borderRadius: "20px",
  fontSize: 13,
  fontWeight: active ? 600 : 500,
  cursor: "pointer",
  border: "1px solid",
  borderColor: active ? "primary.main" : "divider",
  backgroundColor: active ? "primary.main" : "background.paper",
  color: active ? "primary.contrastText" : "text.secondary",
  userSelect: "none",
});

export const timeInputSx = {
  px: "12px",
  py: "9px",
  borderRadius: "10px",
  border: "1.5px solid",
  borderColor: "divider",
  bgcolor: "background.default",
  fontFamily: '"Space Mono", monospace',
  fontSize: 14,
  color: "text.primary",
  outline: "none",
} as const;

export const quietTimeInputSx = {
  px: "11px",
  py: "8px",
  borderRadius: "9px",
  border: "1.5px solid",
  borderColor: "divider",
  bgcolor: "background.paper",
  fontFamily: '"Space Mono", monospace',
  fontSize: 13.5,
  color: "text.primary",
  outline: "none",
} as const;
