export const settingsProfileStyles = {
  root: {
    minHeight: "100vh",
    backgroundColor: "background.default",
    display: "flex",
  },
  shell: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    overflow: "hidden",
  },
  scrollBody: {
    flex: 1,
    overflow: "auto",
    px: { xs: 2, md: 3.75 },
    pt: { xs: 2.5, md: 3.75 },
    pb: { xs: 5, md: 7.5 },
  },
  contentWrap: {
    maxWidth: 940,
    mx: "auto",
    animation: "fadeUp .4s ease both",
  },
  profileSummaryCard: {
    display: "flex",
    alignItems: "center",
    gap: "18px",
    p: "22px 24px",
    mb: "20px",
    borderRadius: "18px",
    boxShadow: "0 1px 2px rgba(24,24,32,.05)",
  },
  profileAvatar: {
    width: 64,
    height: 64,
    flex: "none",
    borderRadius: "50%",
    bgcolor: "primary.main",
    color: "primary.contrastText",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: '"Source Serif 4", serif',
    fontWeight: 700,
    fontSize: 26,
  },
  profileTextWrap: { flex: 1, minWidth: 0 },
  profileName: {
    fontFamily: '"Source Serif 4", serif',
    fontSize: 21,
    fontWeight: 700,
    letterSpacing: "-.01em",
  },
  profileMeta: { fontSize: 13.5, color: "text.secondary" },
  profilePlanChip: {
    fontSize: 11,
    fontWeight: 700,
    px: "12px",
    py: "5px",
    borderRadius: "20px",
    bgcolor: "secondary.light",
    color: "secondary.main",
    fontFamily: '"Space Mono", monospace',
    textTransform: "uppercase",
    letterSpacing: ".06em",
  },
  layoutGrid: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "220px 1fr" },
    gap: "20px",
  },
  tabsCard: {
    p: "10px",
    borderRadius: "16px",
    height: "fit-content",
    boxShadow: "0 1px 2px rgba(24,24,32,.05)",
  },
  tabIndicator: { width: 7, height: 7, borderRadius: "2px" },
  sectionCard: {
    p: "24px 26px",
    borderRadius: "16px",
    boxShadow: "0 1px 2px rgba(24,24,32,.05)",
  },
  sectionTitle: {
    fontFamily: '"Source Serif 4", serif',
    fontSize: 18,
    fontWeight: 600,
  },
  sectionTitleWithGap: {
    fontFamily: '"Source Serif 4", serif',
    fontSize: 18,
    fontWeight: 600,
    mb: "20px",
  },
  profileGrid: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "1fr 1fr" },
    gap: "16px",
  },
  fieldLabel: {
    fontSize: 12,
    letterSpacing: ".06em",
    textTransform: "uppercase",
    color: "text.disabled",
    fontWeight: 700,
    fontFamily: '"Space Mono", monospace',
    mb: "7px",
  },
  actionRow: { display: "flex", gap: "12px", mt: "22px" },
  actionButton: { px: "22px", py: "11px", borderRadius: "11px", fontWeight: 600, fontSize: 14 },
  preferenceRow: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    pb: "18px",
    borderBottom: "1px solid",
    borderColor: "divider",
  },
  grow: { flex: 1 },
  preferenceLabel: { fontWeight: 600, fontSize: 14.5 },
  preferenceSubLabel: { fontSize: 13, color: "text.secondary", mt: "2px" },
  preferenceBlock: { py: "18px", borderBottom: "1px solid", borderColor: "divider" },
  preferenceBlockTitle: { fontWeight: 600, fontSize: 14.5, mb: "12px" },
  chipRow: { display: "flex", gap: "10px", flexWrap: "wrap" },
  accentDot: { width: 10, height: 10, borderRadius: "50%" },
  preferenceTailBlock: { pt: "18px" },
  notificationTitle: {
    fontFamily: '"Source Serif 4", serif',
    fontSize: 18,
    fontWeight: 600,
    mb: "8px",
  },
  notificationRow: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    py: "15px",
    borderTop: "1px solid",
    borderColor: "divider",
  },
  subscriptionCard: {
    p: "24px 26px",
    borderRadius: "16px",
    color: "primary.contrastText",
    backgroundColor: "primary.main",
    boxShadow: "0 4px 20px -8px rgba(24,24,32,.14)",
  },
  subscriptionHeaderRow: { display: "flex", justifyContent: "space-between", alignItems: "flex-start" },
  subscriptionKicker: {
    fontSize: 12,
    letterSpacing: ".12em",
    textTransform: "uppercase",
    opacity: 0.8,
    fontFamily: '"Space Mono", monospace',
  },
  subscriptionPlanName: { fontFamily: '"Source Serif 4", serif', fontSize: 24, fontWeight: 700, mt: "4px" },
  subscriptionPrice: { fontFamily: '"Source Serif 4", serif', fontSize: 22, fontWeight: 700 },
  subscriptionPriceSuffix: { fontSize: 13, opacity: 0.7 },
  subscriptionRenew: { fontSize: 13.5, opacity: 0.9, mt: "12px" },
  subscriptionActions: { display: "flex", gap: "12px", mt: "18px", flexWrap: "wrap" },
  comparePlansButton: {
    px: "20px",
    py: "10px",
    borderRadius: "11px",
    bgcolor: "#fff",
    color: "primary.main",
    fontWeight: 600,
    fontSize: 14,
    "&:hover": { bgcolor: "#fff", opacity: 0.9 },
  },
  cancelPlanButton: {
    px: "20px",
    py: "10px",
    borderRadius: "11px",
    borderColor: "rgba(255,255,255,.35)",
    color: "#fff",
    fontWeight: 600,
    fontSize: 14,
  },
  billingCard: { p: "20px 24px", borderRadius: "16px", mt: "16px" },
  billingTitle: { fontFamily: '"Source Serif 4", serif', fontSize: 16, fontWeight: 600, mb: "6px" },
  billingRow: {
    display: "flex",
    justifyContent: "space-between",
    py: "11px",
    borderTop: "1px solid",
    borderColor: "divider",
    fontSize: 13.5,
  },
  billingDate: { fontSize: 13.5 },
  billingAmount: { color: "text.secondary", fontFamily: '"Space Mono", monospace', fontSize: 13.5 },
  accountRow: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    py: "15px",
    borderTop: "1px solid",
    borderColor: "divider",
  },
  accountTitle: { fontWeight: 600, fontSize: 14.5 },
  accountSubTitle: { fontSize: 13, color: "text.secondary" },
  accountDangerTitle: { fontWeight: 600, fontSize: 14.5, color: "error.main" },
  accountActionButton: { px: "18px", py: "9px", borderRadius: "10px", fontWeight: 600, fontSize: 13.5 },
};

export const settingsTabItemSx = (active: boolean) => ({
  display: "flex",
  alignItems: "center",
  gap: "10px",
  px: "12px",
  py: "10px",
  borderRadius: "11px",
  cursor: "pointer",
  color: active ? "primary.main" : "text.secondary",
  backgroundColor: active ? "primary.light" : "transparent",
  fontWeight: active ? 600 : 500,
  fontSize: 14,
  "&:hover": { backgroundColor: active ? "primary.light" : "background.default" },
});

export const settingsTabIndicatorSx = (active: boolean) => ({
  ...settingsProfileStyles.tabIndicator,
  backgroundColor: active ? "primary.main" : "text.disabled",
});

export const settingsAccentSwatchSx = (active: boolean, color: string) => ({
  display: "inline-flex",
  alignItems: "center",
  gap: "9px",
  px: "12px",
  py: "8px",
  borderRadius: "10px",
  cursor: "pointer",
  border: "1px solid",
  borderColor: active ? color : "divider",
  color: active ? color : "text.secondary",
  backgroundColor: active ? `${color}16` : "background.paper",
  fontWeight: active ? 600 : 500,
  fontSize: 13,
});

export const settingsPillSx = (active: boolean) => ({
  px: "15px",
  py: "8px",
  borderRadius: "20px",
  fontSize: 13,
  fontWeight: active ? 600 : 500,
  cursor: "pointer",
  border: "1px solid",
  borderColor: active ? "primary.main" : "divider",
  backgroundColor: active ? "primary.main" : "background.paper",
  color: active ? "primary.contrastText" : "text.secondary",
  userSelect: "none",
});

export const settingsFieldInputSx = {
  width: "100%",
  px: "15px",
  py: "13px",
  borderRadius: "12px",
  border: "1.5px solid",
  borderColor: "divider",
  backgroundColor: "background.paper",
  fontFamily: '"Plus Jakarta Sans", sans-serif',
  fontSize: 14.5,
  color: "text.primary",
  outline: "none",
} as const;
