import type { SearchTonePalette } from "../../global-search.constants";

export const globalSearchStyles = {
  root: {
    minHeight: "100vh",
    backgroundColor: "background.default",
    display: "flex",
  },
  shell: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    overflow: "hidden",
  },
  scrollBody: {
    flex: 1,
    overflow: "auto",
    px: { xs: 2, md: 3.75 },
    pt: { xs: 2.5, md: 3.75 },
    pb: { xs: 5, md: 7.5 },
  },
  wrap: { maxWidth: 760, mx: "auto" },
  searchInputShell: {
    height: 54,
    borderRadius: "14px",
    borderWidth: "1.5px",
    borderColor: "primary.main",
    px: "18px",
    py: 0,
    display: "flex",
    alignItems: "center",
    gap: "12px",
    backgroundColor: "background.paper",
    boxShadow: "0 1px 2px rgba(24,24,32,.05)",
  },
  searchIcon: {
    width: 17,
    height: 17,
    borderRadius: "50%",
    border: "2px solid",
    borderColor: "text.disabled",
    position: "relative",
    flex: "none",
    '&::after': {
      content: '""',
      position: "absolute",
      width: 8,
      height: 2,
      bgcolor: "text.disabled",
      bottom: -4,
      right: -4,
      transform: "rotate(45deg)",
      borderRadius: "2px",
    },
  },
  searchInput: {
    flex: 1,
    border: "none",
    outline: "none",
    background: "transparent",
    fontFamily: '"Plus Jakarta Sans", sans-serif',
    fontSize: 16,
    color: "text.primary",
  },
  chipsRow: { mt: "18px", mb: "18px", display: "flex", gap: "8px", flexWrap: "wrap" },
  suggestionsWrap: { mt: "26px" },
  suggestionsRow: { display: "flex", gap: "9px", flexWrap: "wrap" },
  suggestionHeading: {
    fontSize: 11,
    letterSpacing: ".12em",
    textTransform: "uppercase",
    color: "text.disabled",
    fontWeight: 700,
    fontFamily: '"Space Mono", monospace',
    mb: "12px",
  },
  noResults: { textAlign: "center", px: "20px", py: "56px" },
  resultsList: { display: "flex", flexDirection: "column", gap: "10px" },
  resultCard: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    bgcolor: "background.paper",
    border: "1px solid",
    borderColor: "divider",
    borderRadius: "14px",
    px: "18px",
    py: "15px",
    cursor: "pointer",
    boxShadow: "0 1px 2px rgba(24,24,32,.05)",
    "&:hover": { borderColor: "primary.main" },
  },
  resultIcon: {
    width: 38,
    height: 38,
    flex: "none",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 16,
    fontWeight: 700,
  },
};

export const typeChipSx = (active: boolean) => ({
  px: "15px",
  py: "8px",
  borderRadius: "20px",
  fontSize: 13,
  cursor: "pointer",
  border: "1px solid",
  borderColor: active ? "primary.main" : "divider",
  bgcolor: active ? "primary.main" : "background.paper",
  color: active ? "primary.contrastText" : "text.secondary",
  fontWeight: active ? 600 : 500,
});

export const suggestionChipSx = {
  px: "15px",
  py: "9px",
  borderRadius: "20px",
  border: "1px solid",
  borderColor: "divider",
  bgcolor: "background.paper",
  fontSize: 13.5,
  cursor: "pointer",
  color: "text.primary",
  "&:hover": { borderColor: "primary.main", color: "primary.main" },
};

export const resultIconToneSx = (tone: SearchTonePalette) => ({
  ...globalSearchStyles.resultIcon,
  bgcolor: tone.bg,
  color: tone.fg,
});

export const resultKindSx = (color: string) => ({
  fontSize: 10,
  letterSpacing: ".08em",
  textTransform: "uppercase",
  fontWeight: 700,
  fontFamily: '"Space Mono", monospace',
  color,
});
